import Footer from "src/components/footer/page";
import "./globals.css";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ooink | Hide and share your links",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="google-adsense-account" content="ca-pub-8146840112267023"/>

        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>
      <body className={inter.className}>
        {children}

        <Footer />

        <Analytics />
      </body>
    </html>
  );
}
