
import Footer from 'src/components/footer/page'
import './globals.css'
import { Inter } from 'next/font/google'
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ooink | Hide and share your links',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes='any'/>
      </head>
      <body className={inter.className}>
        {children}
        <Footer/>
        <Analytics/>
      </body>
    </html>
  )
}
