import Footer from "src/components/footer/page";
import "./globals.css";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { Providers } from "./providers";
// import CircleBg from "src/components/circle-bg/page";
import Image from "next/image";
import CircleBg from "src/components/circleBg/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ooink | Hide and share your links",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-adsense-account" content="ca-pub-8146840112267023" />

        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <Providers>
        <CircleBg />
          {children}
          <Footer />
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
